# Generated by Django 4.2 on 2025-06-21 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_address', models.CharField(max_length=100, unique=True, verbose_name='Адрес')),
                ('longitude', models.DecimalField(decimal_places=17, max_digits=20, verbose_name='Долгота')),
                ('latitude', models.DecimalField(decimal_places=17, max_digits=20, verbose_name='Широта')),
                ('created_at', models.DateField(auto_now=True, verbose_name='Дата запроса')),
            ],
        ),
    ]
