# Generated by Django 4.2 on 2025-06-21 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locationapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='location',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Долгота'),
        ),
    ]
