# Generated by Django 3.1.4 on 2020-12-14 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("foodcartapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={"verbose_name": "Заказ", "verbose_name_plural": "Заказы"},
        ),
        migrations.AlterModelOptions(
            name="orderproduct",
            options={
                "verbose_name": "Позиция заказа",
                "verbose_name_plural": "Позиции заказа",
            },
        ),
    ]
