# Generated by Django 3.1.4 on 2020-12-19 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("foodcartapp", "0006_auto_20201219_2224"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="created_at",
        ),
    ]
