# Generated by Django 3.2.15 on 2022-08-15 06:31

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0039_auto_20220813_1252'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='orderline',
            managers=[
                ('orders', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='orderline',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Цена'),
            preserve_default=False,
        ),
    ]
