# Generated by Django 4.2 on 2025-06-20 09:09

from django.db import migrations


def fill_price_at_order(apps, schema_editor):
    OrderItem = apps.get_model('foodcartapp', 'OrderItem')
    items = OrderItem.objects.select_related('product').filter(price_at_order__isnull=True)

    for item in items.iterator():
        item.price_at_order = item.product.price
        OrderItem.objects.filter(pk=item.pk).update(price_at_order=item.price_at_order)


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0039_orderitem_price_at_order'),
    ]

    operations = [
        migrations.RunPython(fill_price_at_order),
    ]
