# Generated by Django 3.2.15 on 2023-03-10 20:16

from django.db import migrations


def add_prices(apps, schema_editor):
    ProductOrder = apps.get_model('foodcartapp', 'ProductOrder')
    for product_order in ProductOrder.objects.prefetch_related('product').iterator():
        product_order.product_price = product_order.product.price
        product_order.save()


def reverse(apps, schema_editor):
    ProductOrder = apps.get_model('foodcartapp', 'ProductOrder')
    for product_order in ProductOrder.objects.iterator():
        product_order.product_price = 0
        product_order.save()


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0039_auto_20230310_2031'),
    ]

    operations = [
        migrations.RunPython(add_prices, reverse),
    ]
