# Generated by Django 3.2.15 on 2023-03-11 20:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0040_auto_20230310_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Не обработан'), (1, 'Готовится'), (2, 'В пути'), (3, 'Доставлен')], default=0, verbose_name='статус'),
        ),
        migrations.AlterField(
            model_name='productorder',
            name='product_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='цена товара'),
        ),
    ]
