# Generated by Django 4.2 on 2025-06-20 15:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0040_fixed_the_cost_of_the_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Необработанный'), ('in_progress', 'В работе'), ('delivery', 'Доставка'), ('completed', 'Выполнен'), ('canceled', 'Отменен')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price_at_order',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена'),
        ),
    ]
