# Generated by Django 3.2.15 on 2023-03-11 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0041_auto_20230311_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Не обработан'), (1, 'Готовится'), (2, 'В пути'), (3, 'Доставлен')], db_index=True, default=0, verbose_name='статус'),
        ),
    ]
