# Generated by Django 4.2 on 2025-06-20 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0041_order_status_alter_orderitem_price_at_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, null=True, max_length=100, verbose_name='Комментарий'),
        ),
    ]
