# Generated by Django 3.2.15 on 2022-08-16 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0043_alter_orderline_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderline',
            name='status',
            field=models.CharField(choices=[('CR', 'Создан'), ('PC', 'Сборка'), ('SH', 'Доставка'), ('CT', 'Выполнен')], default='CR', max_length=2),
        ),
    ]
