# Generated by Django 4.2 on 2025-06-20 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0043_order_called_at_order_created_at_order_delivered_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.CharField(choices=[('cash', 'Наличностью'), ('e_pay', 'Электронно')], default='cash', max_length=20, verbose_name='Тип оплаты'),
        ),
    ]
