# Generated by Django 4.2 on 2025-06-20 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0044_order_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, default='', max_length=100, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Необработанный'), ('in_progress', 'В работе'), ('delivery', 'Доставка'), ('completed', 'Выполнен'), ('canceled', 'Отменен')], default='pending', max_length=20, verbose_name='Статус заказа'),
        ),
    ]
