# Generated by Django 3.2.15 on 2022-08-16 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0044_orderline_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderline',
            name='status',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('CR', 'Создан'), ('PC', 'Сборка'), ('SH', 'Доставка'), ('CT', 'Выполнен')], default='CR', max_length=2),
        ),
    ]
