# Generated by Django 3.2.15 on 2022-08-17 10:30

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0045_auto_20220816_1542'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='order',
            managers=[
                ('price', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='orderline',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, max_length=200, verbose_name='комментарий'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('CR', 'Создан'), ('PC', 'Сборка'), ('SH', 'Доставка'), ('CT', 'Выполнен')], db_index=True, default='CR', max_length=2),
        ),
    ]
