# Generated by Django 4.2 on 2025-06-21 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0046_order_restaurant_prepare'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='restaurant_prepare',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cooking', to='foodcartapp.restaurant', verbose_name='Ресторан готовит'),
        ),
    ]
