# Generated by Django 4.2 on 2025-06-23 17:37

from django.db import migrations


def replace_null_with_empty(apps, schema_editor):
    Model = apps.get_model('foodcartapp', 'Order')
    Model.objects.filter(comment__isnull=True).update(comment='')


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0047_alter_order_restaurant_prepare'),
    ]

    operations = [
        migrations.RunPython(replace_null_with_empty),
    ]