# Generated by Django 3.2.15 on 2022-08-19 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0048_order_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cook_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='foodcartapp.restaurant'),
        ),
        migrations.AddField(
            model_name='order',
            name='status_int',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Создан'), (2, 'Сборка'), (3, 'Доставка'), (4, 'Выполнен')], db_index=True, default=1),
        ),
    ]
