# Generated by Django 3.2.15 on 2022-08-20 09:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0050_remove_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='called_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Согласован'),
        ),
        migrations.AlterField(
            model_name='order',
            name='cook_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='foodcartapp.restaurant', verbose_name='Исполнитель'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivered_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Доставлен'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phonenumber',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status_int',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Создан'), (2, 'Сборка'), (3, 'Доставка'), (4, 'Выполнен')], db_index=True, default=1, verbose_name='Статус заказа'),
        ),
    ]
