# Generated by Django 3.2.15 on 2022-08-30 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0054_alter_order_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cook_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='foodcartapp.restaurant', verbose_name='Исполнитель'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('CASH', 'наличные'), ('CARD', 'электронно')], db_index=True, max_length=4, verbose_name='способ оплаты'),
        ),
    ]
