# Generated by Django 3.2.15 on 2022-09-05 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0056_alter_order_managers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='status_int',
            new_name='status',
        ),
    ]
